return {
  "sphamba/smear-cursor.nvim",
  opts = {
    -- cursor_color = "#586E75",
    cursor_color = "none",
    stiffness = 0.8,
    trailing_stiffness = 0.5,
    distance_stop_animating = 0.5,
    trailing_exponent = 5,
    damping = 0.8,
    hide_target_hack = true,
    gamma = 1,
    smear_between_buffers = true,
    smear_between_neighbor_lines = true,
    scroll_buffer_space = true,
    legacy_computing_symbols_support = true,
    never_draw_over_target = true,
    smear_insert_mode = true,
  },
}
